[#161] Implement display of new address types
zcash/secant-android-wallet pull request #691
Opened 2022-12-16 13:59 UTC by gasstan

> **Note**
>This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] **Self-review** your own code in GitHub's web interface[^1]
- [ ] Add **automated tests** as appropriate
- [ ] Update the [**manual tests**](../blob/main/docs/testing/manual_testing)[^2] as appropriate
- [ ] Check the **code coverage**[^3] report for the automated tests
- [ ] Update **documentation** as appropriate (e.g [README.md](../blob/main/README.md), and [**Architecture.md**](../blob/main/docs/Architecture.md), etc.)
- [ ] **Run the app** and try the changes
- [ ] Pull in the latest changes from the **main** branch and **squash** your commits before assigning a reviewer[^4]

> **Note**
> It is good practice to provide before and after UI  **screenshots** in the description of this PR. This is only applicable for changes that modify the UI.

# Reviewer

- [ ] Check the code with the [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md) **checklist**
- [ ] Perform an **ad hoc review**[^5]
- [ ] Review the **automated tests**
- [ ] Review the **manual tests**
- [ ] Review the **documentation**, [**README.md**](../blob/main/README.md), and [**Architecture.md**](../blob/main/docs/Architecture.md) as appropriate
- [ ] **Run the app** and try the changes[^6]

[^1]: _Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs._
[^2]: _While we aim for automated testing of the application, some aspects require manual testing. If you had to manually test something during development of this pull request, write those steps down._
[^3]: _While we are not looking for perfect coverage, the tool can point out potential cases that have been missed. Code coverage can be generated with: `./gradlew check` for Kotlin modules and `./gradlew connectedCheck -PIS_ANDROID_INSTRUMENTATION_TEST_COVERAGE_ENABLED=true` for Android modules._
[^4]: _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit._
[^5]: _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
[^6]: _While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data. Perform this step last, after verifying the code changes are safe to run locally._

2022-12-16 14:12 UTC, ccjernigan requested changes

2022-12-16 14:12 UTC, ccjernigan commented on sdk-ext-lib/src/main/java/cash/z/ecc/sdk/model/WalletAddresses.kt
>              // TODO [#161]: Pending SDK support, fix providing correct values for the unified
TODO comments should be deleted once a fix for them is implemented.

2022-12-16 14:12 UTC, ccjernigan commented on sdk-ext-lib/src/main/java/cash/z/ecc/sdk/fixture/WalletAddressFixture.kt
> +@Suppress("MaxLineLength")
Can we narrow the scope to the specific item, rather than for the entire class?

2023-01-03 14:49 UTC, HonzaR approved these changes
I just added a link to a TODO comment and checked the middle ellipsized text support in the current version of Jetpack Compose. Unfortunately, it's still not supported, so I've added this information to our related filed [issue](https://github.com/zcash/secant-android-wallet/issues/163#issuecomment-1369797172).

Other than that, it looks good to me.

2023-01-09 12:57 UTC, ccjernigan approved these changes

2023-01-09 12:57 UTC, merged